'use client';

import { useState, useCallback } from 'react';
import Link from 'next/link';
import { FaDocker, FaCopy, FaDownload, FaCheck } from 'react-icons/fa';

// ─── Types ──────────────────────────────────────────────────────────────────

type Language = 'nodejs' | 'python' | 'java' | 'go' | 'php' | 'ruby' | 'dotnet';
type PackageManager = 'npm' | 'yarn' | 'pnpm' | 'pip' | 'poetry' | 'maven' | 'gradle';
type BaseImage = 'alpine' | 'slim' | 'ubuntu' | 'default';

interface FormState {
  language: Language;
  packageManager: PackageManager;
  baseImage: BaseImage;
  port: string;
  multiStage: boolean;
  startCommand: string;
  envVars: string; // comma separated list
}

// ─── Generator Logic ────────────────────────────────────────────────────────

function generateDockerfile(f: FormState): string {
  let dockerfile = `# Dockerfile
# Generated by DevOps Duoo - Dockerfile Generator
# https://devopsduoo.com/tools/dockerfile-generator
`;

  const portStr = f.port ? `\nEXPOSE ${f.port}` : '';
  const envStr = f.envVars 
    ? '\n' + f.envVars.split(',').map(e => `ENV ${e.trim()}`).join('\n')
    : '';

  // Node.js
  if (f.language === 'nodejs') {
    const pm = f.packageManager as 'npm' | 'yarn' | 'pnpm';
    const tag = f.baseImage === 'alpine' ? '20-alpine' : f.baseImage === 'slim' ? '20-slim' : '20';
    const startCmd = f.startCommand || (pm === 'npm' ? 'npm start' : pm === 'yarn' ? 'yarn start' : 'pnpm start');

    if (f.multiStage) {
      dockerfile += `
# Stage 1: Build
FROM node:${tag} AS builder
WORKDIR /app

# Copy package files
COPY package.json ${pm === 'yarn' ? 'yarn.lock' : pm === 'pnpm' ? 'pnpm-lock.yaml' : 'package-lock.json*'} ./
RUN ${pm === 'npm' ? 'npm ci' : pm === 'yarn' ? 'yarn install --frozen-lockfile' : 'npm i -g pnpm && pnpm install --frozen-lockfile'}

# Copy source code and build
COPY . .
RUN ${pm === 'npm' ? 'npm run build' : pm === 'yarn' ? 'yarn build' : 'pnpm build'}

# Stage 2: Production
FROM node:${tag}
WORKDIR /app
${envStr}
ENV NODE_ENV=production

# Copy built assets and dependencies
COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    } else {
      dockerfile += `
FROM node:${tag}
WORKDIR /app
${envStr}

COPY package.json ${pm === 'yarn' ? 'yarn.lock' : pm === 'pnpm' ? 'pnpm-lock.yaml' : 'package-lock.json*'} ./
RUN ${pm === 'npm' ? 'npm install' : pm === 'yarn' ? 'yarn install' : 'npm i -g pnpm && pnpm install'}

COPY . .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    }
  }

  // Python
  else if (f.language === 'python') {
    const pm = f.packageManager as 'pip' | 'poetry';
    const tag = f.baseImage === 'alpine' ? '3.12-alpine' : f.baseImage === 'slim' ? '3.12-slim' : '3.12';
    const startCmd = f.startCommand || 'python main.py';

    if (f.multiStage) {
      dockerfile += `
# Stage 1: Build dependencies
FROM python:${tag} AS builder
WORKDIR /app

# Install build dependencies
${f.baseImage === 'alpine' ? 'RUN apk add --no-cache gcc musl-dev libffi-dev' : 'RUN apt-get update && apt-get install -y gcc'}

# Install packages
RUN pip install --upgrade pip
${pm === 'poetry' ? 'RUN pip install poetry\nCOPY pyproject.toml poetry.lock ./\nRUN poetry export -f requirements.txt --output requirements.txt' : 'COPY requirements.txt ./'}
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

# Stage 2: Runtime
FROM python:${tag}
WORKDIR /app
${envStr}
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .
RUN pip install --no-cache /wheels/*

COPY . .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    } else {
      dockerfile += `
FROM python:${tag}
WORKDIR /app
${envStr}
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    }
  }

  // Go
  else if (f.language === 'go') {
    const tag = f.baseImage === 'alpine' ? '1.22-alpine' : f.baseImage === 'slim' ? '1.22-slim' : '1.22';
    const runtimeTag = f.baseImage === 'alpine' ? 'alpine:latest' : f.baseImage === 'slim' ? 'debian:bookworm-slim' : 'debian:bookworm-slim';
    const startCmd = f.startCommand || './app';

    if (f.multiStage) {
      dockerfile += `
# Stage 1: Build
FROM golang:${tag} AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# Stage 2: Runtime
FROM ${runtimeTag}
${f.baseImage === 'alpine' ? 'RUN apk --no-cache add ca-certificates' : 'RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*'}
WORKDIR /root/
${envStr}

COPY --from=builder /app/app .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    } else {
      dockerfile += `
FROM golang:${tag}
WORKDIR /app
${envStr}

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    }
  }

  // Java
  else if (f.language === 'java') {
    const pm = f.packageManager as 'maven' | 'gradle';
    const tag = f.baseImage === 'alpine' ? '17-alpine' : '17';
    const startCmd = f.startCommand || 'java -jar app.jar';

    if (f.multiStage) {
      dockerfile += `
# Stage 1: Build
${pm === 'maven' ? 'FROM maven:3.9-eclipse-temurin-17 AS builder' : 'FROM gradle:8-jdk17 AS builder'}
WORKDIR /app

COPY . .
${pm === 'maven' ? 'RUN mvn clean package -DskipTests' : 'RUN gradle build --no-daemon -x test'}

# Stage 2: Runtime
FROM eclipse-temurin:${tag}
WORKDIR /app
${envStr}

${pm === 'maven' ? 'COPY --from=builder /app/target/*.jar app.jar' : 'COPY --from=builder /app/build/libs/*.jar app.jar'}
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    } else {
      dockerfile += `
FROM eclipse-temurin:${tag}
WORKDIR /app
${envStr}

COPY target/*.jar app.jar
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
    }
  }
  
  // PHP
  else if (f.language === 'php') {
    const tag = f.baseImage === 'alpine' ? '8.3-fpm-alpine' : '8.3-fpm';
    const startCmd = f.startCommand || 'php-fpm';
    
    dockerfile += `
FROM php:${tag}
WORKDIR /var/www/html
${envStr}

# Install dependencies
${f.baseImage === 'alpine' ? 'RUN apk add --no-cache zip unzip git libpng-dev && docker-php-ext-install pdo pdo_mysql gd' : 'RUN apt-get update && apt-get install -y zip unzip git libpng-dev && docker-php-ext-install pdo pdo_mysql gd'}

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

COPY . .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
  }
  
  // Ruby
  else if (f.language === 'ruby') {
    const tag = f.baseImage === 'alpine' ? '3.3-alpine' : '3.3-slim';
    const startCmd = f.startCommand || 'rails server -b 0.0.0.0';

    dockerfile += `
FROM ruby:${tag}
WORKDIR /app
${envStr}
ENV RAILS_ENV=production

# Install dependencies
${f.baseImage === 'alpine' ? 'RUN apk add --no-cache build-base tzdata sqlite-dev' : 'RUN apt-get update -qq && apt-get install -y build-essential libsqlite3-dev'}

COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test

COPY . .
${portStr}
CMD ["${startCmd.split(' ').join('", "')}"]
`;
  }
  
  // .NET
  else if (f.language === 'dotnet') {
    const tag = f.baseImage === 'alpine' ? '8.0-alpine' : '8.0';
    const startCmd = f.startCommand || 'dotnet App.dll';

    if (f.multiStage) {
      dockerfile += `
# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:${tag} AS builder
WORKDIR /src

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app/publish

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:${tag}
WORKDIR /app
${envStr}

COPY --from=builder /app/publish .
${portStr}
ENTRYPOINT ["${startCmd.split(' ').join('", "')}"]
`;
    } else {
      dockerfile += `
FROM mcr.microsoft.com/dotnet/aspnet:${tag}
WORKDIR /app
${envStr}

COPY /publish .
${portStr}
ENTRYPOINT ["${startCmd.split(' ').join('", "')}"]
`;
    }
  }

  return dockerfile;
}

// ─── Component ───────────────────────────────────────────────────────────────

const defaultForm: FormState = {
  language: 'nodejs',
  packageManager: 'npm',
  baseImage: 'alpine',
  port: '3000',
  multiStage: true,
  startCommand: '',
  envVars: '',
};

export default function DockerfileGenerator() {
  const [form, setForm] = useState<FormState>(defaultForm);
  const [copied, setCopied] = useState(false);
  const [generated, setGenerated] = useState(false);
  const [dockerfile, setDockerfile] = useState('');

  const update = useCallback((key: keyof FormState, value: any) => {
    setForm(prev => {
      const next = { ...prev, [key]: value };
      // Handle PM defaults based on language
      if (key === 'language') {
        if (value === 'nodejs') next.packageManager = 'npm';
        if (value === 'python') next.packageManager = 'pip';
        if (value === 'java') next.packageManager = 'maven';
      }
      return next;
    });
    setGenerated(false);
  }, []);

  const handleGenerate = useCallback(() => {
    const result = generateDockerfile(form);
    setDockerfile(result);
    setGenerated(true);
  }, [form]);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(dockerfile);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  }, [dockerfile]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([dockerfile], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Dockerfile';
    a.click();
    URL.revokeObjectURL(url);
  }, [dockerfile]);

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Hero */}
      <section className="bg-gradient-to-br from-gray-900 via-blue-950 to-indigo-900 text-white py-14 sm:py-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 bg-blue-500/20 border border-blue-400/30 text-blue-300 text-sm font-medium px-4 py-1.5 rounded-full mb-6">
            <span className="w-2 h-2 bg-blue-400 rounded-full animate-pulse" />
            Free DevOps Tool
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-5 leading-tight">
            Dockerfile Generator
          </h1>
          <p className="text-lg sm:text-xl text-blue-100 max-w-3xl mx-auto leading-relaxed">
            Generate production-ready, highly optimized Dockerfiles for your projects. Supports multi-stage builds, minimal base images, and best practices.
          </p>
        </div>
      </section>

      {/* Main Tool */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-14">
        <div className="grid lg:grid-cols-2 gap-8 items-start">
          
          {/* ── LEFT: Form ─────────────────────────────────────────────── */}
          <div className="space-y-6">
            
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 p-6">
              <h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-4">1. Environment</h2>
              
              <div className="mb-5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Language / Framework</label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  {[
                    { value: 'nodejs', label: 'Node.js', icon: '🟢' },
                    { value: 'python', label: 'Python', icon: '🐍' },
                    { value: 'go', label: 'Go', icon: '🐹' },
                    { value: 'java', label: 'Java', icon: '☕' },
                    { value: 'php', label: 'PHP', icon: '🐘' },
                    { value: 'ruby', label: 'Ruby', icon: '💎' },
                    { value: 'dotnet', label: '.NET', icon: '🟣' },
                  ].map(l => (
                    <button
                      key={l.value}
                      onClick={() => update('language', l.value)}
                      className={`px-3 py-2 text-sm rounded-xl border flex items-center gap-2 transition-all ${form.language === l.value ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-500 text-blue-700 dark:text-blue-300 font-semibold' : 'border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-gray-600 text-gray-700 dark:text-gray-300'}`}
                    >
                      <span>{l.icon}</span> {l.label}
                    </button>
                  ))}
                </div>
              </div>

              {(form.language === 'nodejs' || form.language === 'python' || form.language === 'java') && (
                <div className="mb-5">
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Package Manager</label>
                  <div className="flex gap-2">
                    {form.language === 'nodejs' && ['npm', 'yarn', 'pnpm'].map(pm => (
                      <button key={pm} onClick={() => update('packageManager', pm)} className={`px-4 py-2 text-sm rounded-xl border transition-all ${form.packageManager === pm ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-500 text-blue-700 dark:text-blue-300 font-semibold' : 'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300'}`}>{pm}</button>
                    ))}
                    {form.language === 'python' && ['pip', 'poetry'].map(pm => (
                      <button key={pm} onClick={() => update('packageManager', pm)} className={`px-4 py-2 text-sm rounded-xl border transition-all ${form.packageManager === pm ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-500 text-blue-700 dark:text-blue-300 font-semibold' : 'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300'}`}>{pm}</button>
                    ))}
                    {form.language === 'java' && ['maven', 'gradle'].map(pm => (
                      <button key={pm} onClick={() => update('packageManager', pm)} className={`px-4 py-2 text-sm rounded-xl border transition-all ${form.packageManager === pm ? 'bg-blue-50 dark:bg-blue-900/30 border-blue-500 text-blue-700 dark:text-blue-300 font-semibold' : 'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300'}`}>{pm}</button>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-700 p-6">
              <h2 className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-4">2. Configuration</h2>
              
              <div className="grid grid-cols-2 gap-4 mb-5">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Base Image</label>
                  <select 
                    value={form.baseImage} 
                    onChange={e => update('baseImage', e.target.value)}
                    className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2 text-sm text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none"
                  >
                    <option value="alpine">Alpine (Smallest)</option>
                    <option value="slim">Slim (Recommended)</option>
                    <option value="default">Default / Ubuntu</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Exposed Port</label>
                  <input 
                    type="text" 
                    value={form.port} 
                    onChange={e => update('port', e.target.value)}
                    placeholder="e.g. 3000"
                    className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2 text-sm text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none"
                  />
                </div>
              </div>

              <div className="mb-5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Custom Start Command (Optional)</label>
                <input 
                  type="text" 
                  value={form.startCommand} 
                  onChange={e => update('startCommand', e.target.value)}
                  placeholder="e.g. npm run serve"
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2 text-sm text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>
              
              <div className="mb-5">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Environment Variables (Comma Separated)</label>
                <input 
                  type="text" 
                  value={form.envVars} 
                  onChange={e => update('envVars', e.target.value)}
                  placeholder="e.g. NODE_ENV=production, DEBUG=true"
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-xl px-4 py-2 text-sm text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <label className="flex items-center gap-3 cursor-pointer p-3 rounded-xl border border-gray-200 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-750 transition-colors">
                <input 
                  type="checkbox" 
                  checked={form.multiStage} 
                  onChange={e => update('multiStage', e.target.checked)}
                  className="w-4 h-4 text-blue-600 rounded"
                />
                <div>
                  <span className="block text-sm font-medium text-gray-900 dark:text-white">Use Multi-Stage Build</span>
                  <span className="block text-xs text-gray-500 dark:text-gray-400">Reduces final image size significantly (Recommended)</span>
                </div>
              </label>
            </div>

            <button 
              onClick={handleGenerate}
              className="w-full py-4 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-2xl font-bold shadow-lg shadow-blue-500/25 transition-all transform hover:-translate-y-0.5"
            >
              Generate Dockerfile
            </button>

          </div>

          {/* ── RIGHT: Preview ───────────────────────────────────────────── */}
          <div className="sticky top-24">
            <div className="bg-[#1e1e2e] rounded-2xl overflow-hidden shadow-2xl border border-gray-800">
              
              {/* Header */}
              <div className="bg-[#181825] px-4 py-3 border-b border-gray-800 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FaDocker className="text-blue-400 text-xl" />
                  <span className="text-gray-300 font-mono text-sm">Dockerfile</span>
                </div>
                {generated && (
                  <div className="flex gap-2">
                    <button 
                      onClick={handleCopy}
                      className="p-2 text-gray-400 hover:text-white hover:bg-gray-700 rounded-lg transition-colors"
                      title="Copy to clipboard"
                    >
                      {copied ? <FaCheck className="text-green-400" /> : <FaCopy />}
                    </button>
                    <button 
                      onClick={handleDownload}
                      className="p-2 text-gray-400 hover:text-white hover:bg-gray-700 rounded-lg transition-colors"
                      title="Download file"
                    >
                      <FaDownload />
                    </button>
                  </div>
                )}
              </div>

              {/* Code */}
              <div className="p-4 sm:p-6 overflow-x-auto min-h-[400px]">
                {generated ? (
                  <pre className="text-sm font-mono text-gray-300 leading-relaxed">
                    <code>
                      {dockerfile.split('\n').map((line, i) => {
                        let colorClass = 'text-gray-300';
                        if (line.startsWith('#')) colorClass = 'text-gray-500';
                        else if (line.startsWith('FROM') || line.startsWith('WORKDIR') || line.startsWith('COPY') || line.startsWith('RUN') || line.startsWith('CMD') || line.startsWith('EXPOSE') || line.startsWith('ENV') || line.startsWith('ENTRYPOINT')) {
                           colorClass = 'text-blue-400 font-bold';
                        }
                        
                        const isKeyword = colorClass !== 'text-gray-300' && colorClass !== 'text-gray-500';
                        const parts = isKeyword ? line.split(' ') : [line];
                        
                        return (
                          <div key={i} className="whitespace-pre">
                            {isKeyword ? (
                              <>
                                <span className={colorClass}>{parts[0]}</span>
                                {' '}
                                <span className="text-green-300">{parts.slice(1).join(' ')}</span>
                              </>
                            ) : (
                              <span className={colorClass}>{line}</span>
                            )}
                          </div>
                        );
                      })}
                    </code>
                  </pre>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-gray-500 mt-20">
                    <FaDocker className="text-6xl mb-4 opacity-20" />
                    <p>Select your options and click generate</p>
                  </div>
                )}
              </div>
            </div>
          </div>

        </div>
      </main>
    </div>
  );
}
